# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Clarisa Romero
email: cclarisaromero@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ingeniera en Sistemas de Información
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://clarisaromero.com" # the base hostname & protocol for your site
twitter_username: risaclaa
github_username:  clarii
instagram_username: risacla
linkedin_link: https://www.linkedin.com/in/clarisa-romero-ab817057
facebook_link: https://www.facebook.com/clari.010

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman